spring:
  datasource:
    url: jdbc:mysql://localhost:3306/trixi
    username: admin
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

